#!/usr/bin/env python3

import os.path
import subprocess

import util


if __name__ == '__main__':
  repo_dir = util.run_command('git rev-parse --show-toplevel')
  paths_str = util.run_command('git show --stat --pretty=format: --name-only')
  paths = [ os.path.join(repo_dir, x) for x in  paths_str.split('\n')]
  for path in paths:
    util.run_command('subl %s' % path)
